backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/"
media_library:
  name: about
publish_mode: editorial_workflow

collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "content/about"
  create: false
  slug: "{{slug}}"
  file: "content/about/about.md"
  fields:
      - {label: "type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "body", name: "body", widget: "markdown"}
