backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/"
media_library:
  name: uploads
publish_mode: editorial_workflow

collections:
- name: "about" # Used in routes, e.g., /admin/collections/blog
  label: "About" # Used in the UI
  label_singular: 'About' # Used in the UI, ie: "New Post"
  description: >
      Disini tempat naro biodata, kisah hidup atau apapun itulah... :D
  folder: "content/about"
  create: false
  slug: "{{slug}}"
  file: "content/about/about.md"
  fields:
      - {label: "type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "body", name: "body", widget: "markdown"}

- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Posts" # Used in the UI
  label_singular: 'post' # Used in the UI, ie: "New Post"
  description: >
      Halaman yang berisi postingan. Ditempat ini kamu dapat melakukan berbagai perubahan terhadap post yang sudah ada atau menghapusnya. Oiya, untuk tipe post nanti diberikan 2 pilihan, antara featured dan post biasa. Kalau featured itu yang akan tampil di halaman paling atas, biasanya sih jumlahnya cuman 3 buah.
  folder: "content/blog"
  create: true
  slug: "{{year}}-{{month}}-{{slug}}"
  fields:
      - label: "type"
        name: "type"
        widget: "select"
        options: ["featured", "post"]
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Kategori", name: "categories", widget: "list", allow_add: true}
      - {label: "body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["new"]}
