backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/"
media_library:
  name: about
publish_mode: editorial_workflow

collections:
- name: "about" # Used in routes, e.g., /admin/collections/blog
  label: "About" # Used in the UI
  folder: "content/about"
  create: false
  slug: "{{slug}}"
  file: "content/about/about.md"
  fields:
      - {label: "type", name: "type", widget: "hidden", default: "blog"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "body", name: "body", widget: "markdown"}

- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Post" # Used in the UI
  folder: "content/blog"
  create: true
  slug: "{{slug}}"
  file: "content/blog/_index.md"
  fields:
      - label: "type"
        name: "type"
        widget: "select"
        options: ["featured", "post"]
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Kategori", name: "categories", widget: "string"}
      - {label: "body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["new"]}
